version: '2'
services:
    db:
        image: postgres:15
        volumes:
            - sample_db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=sample
            - POSTGRES_USER=sample
            - POSTGRES_DB=sample
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - 127.0.0.1:5432:5432
volumes:
    sample_db: {}
